// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBmeHAOBJXqvqAtFbaPoF3mh97H0QtQ4U',
    appId: '1:673923452538:web:9909775b25346cdccfb5c3',
    messagingSenderId: '673923452538',
    projectId: 'zara-ecommerce-app',
    authDomain: 'zara-ecommerce-app.firebaseapp.com',
    storageBucket: 'zara-ecommerce-app.appspot.com',
    measurementId: 'G-SLQ8TD21NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSuI9OXomBhd27g5kEzimiaXv8qKJdoWA',
    appId: '1:673923452538:android:19a0f935a13087f5cfb5c3',
    messagingSenderId: '673923452538',
    projectId: 'zara-ecommerce-app',
    storageBucket: 'zara-ecommerce-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARyg0bwBUkwb1udLfZiA8jdeYfEc1yh3I',
    appId: '1:673923452538:ios:705621629b61c6decfb5c3',
    messagingSenderId: '673923452538',
    projectId: 'zara-ecommerce-app',
    storageBucket: 'zara-ecommerce-app.appspot.com',
    iosClientId: '673923452538-a7g0csicmpk5mo0uf1b5aoeekmb96lf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARyg0bwBUkwb1udLfZiA8jdeYfEc1yh3I',
    appId: '1:673923452538:ios:705621629b61c6decfb5c3',
    messagingSenderId: '673923452538',
    projectId: 'zara-ecommerce-app',
    storageBucket: 'zara-ecommerce-app.appspot.com',
    iosClientId: '673923452538-a7g0csicmpk5mo0uf1b5aoeekmb96lf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );
}
